"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

setup(
    name='WeChat Downloads',
    app=['test.py'],
    data_files=['config.json', ('images',['images/icon.icns'])],
    options={
        'py2app': {
            'iconfile': 'images/icon.icns',
            'plist': {
                'LSBackgroundOnly': True,
                'CFBundleIdentifier': 'com.jameslee.watch_wechat_files',
            }
        }
    },
    setup_requires=['py2app'],
)
